"""create_forum_tables

Revision ID: 412120d6733a
Revises: 15325a75a2d5
Create Date: 2025-11-22 17:50:28.508976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '412120d6733a'
down_revision = '15325a75a2d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forum_categories', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_forum_categories_slug', table_name='forum_categories')
    op.drop_column('forum_categories', 'slug')
    op.create_index('ix_forum_likes_post_user', 'forum_likes', ['post_id', 'user_id'], unique=True)
    op.create_index('ix_forum_likes_user', 'forum_likes', ['user_id'], unique=False)
    op.drop_constraint('forum_likes_user_id_fkey', 'forum_likes', type_='foreignkey')
    op.drop_constraint('forum_likes_post_id_fkey', 'forum_likes', type_='foreignkey')
    op.create_foreign_key(None, 'forum_likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'forum_likes', 'forum_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('forum_posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('forum_posts', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_forum_posts_created_at', table_name='forum_posts')
    op.create_index('ix_forum_posts_parent', 'forum_posts', ['parent_id'], unique=False)
    op.create_index('ix_forum_posts_thread_created', 'forum_posts', ['thread_id', 'created_at'], unique=False)
    op.create_index('ix_forum_posts_user', 'forum_posts', ['user_id'], unique=False)
    op.drop_constraint('forum_posts_thread_id_fkey', 'forum_posts', type_='foreignkey')
    op.drop_constraint('forum_posts_author_id_fkey', 'forum_posts', type_='foreignkey')
    op.drop_constraint('forum_posts_parent_id_fkey', 'forum_posts', type_='foreignkey')
    op.create_foreign_key(None, 'forum_posts', 'forum_threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'forum_posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'forum_posts', 'forum_posts', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('forum_posts', 'is_deleted')
    op.drop_column('forum_posts', 'likes_count')
    op.drop_column('forum_posts', 'author_id')
    op.drop_column('forum_posts', 'is_best_answer')
    op.add_column('forum_threads', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('forum_threads', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('forum_threads', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.drop_index('ix_forum_threads_created_at', table_name='forum_threads')
    op.drop_index('ix_forum_threads_title', table_name='forum_threads')
    op.create_index('ix_forum_threads_category_created', 'forum_threads', ['category_id', 'created_at'], unique=False)
    op.create_index('ix_forum_threads_user', 'forum_threads', ['user_id'], unique=False)
    op.drop_constraint('forum_threads_category_id_fkey', 'forum_threads', type_='foreignkey')
    op.drop_constraint('forum_threads_author_id_fkey', 'forum_threads', type_='foreignkey')
    op.create_foreign_key(None, 'forum_threads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'forum_threads', 'forum_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('forum_threads', 'views_count')
    op.drop_column('forum_threads', 'last_post_at')
    op.drop_column('forum_threads', 'is_locked')
    op.drop_column('forum_threads', 'is_solved')
    op.drop_column('forum_threads', 'posts_count')
    op.drop_column('forum_threads', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_threads', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('forum_threads', sa.Column('posts_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('forum_threads', sa.Column('is_solved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('forum_threads', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('forum_threads', sa.Column('last_post_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('forum_threads', sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'forum_threads', type_='foreignkey')
    op.drop_constraint(None, 'forum_threads', type_='foreignkey')
    op.create_foreign_key('forum_threads_author_id_fkey', 'forum_threads', 'users', ['author_id'], ['id'])
    op.create_foreign_key('forum_threads_category_id_fkey', 'forum_threads', 'forum_categories', ['category_id'], ['id'])
    op.drop_index('ix_forum_threads_user', table_name='forum_threads')
    op.drop_index('ix_forum_threads_category_created', table_name='forum_threads')
    op.create_index('ix_forum_threads_title', 'forum_threads', ['title'], unique=False)
    op.create_index('ix_forum_threads_created_at', 'forum_threads', ['created_at'], unique=False)
    op.drop_column('forum_threads', 'is_closed')
    op.drop_column('forum_threads', 'views')
    op.drop_column('forum_threads', 'user_id')
    op.add_column('forum_posts', sa.Column('is_best_answer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('forum_posts', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('forum_posts', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('forum_posts', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'forum_posts', type_='foreignkey')
    op.drop_constraint(None, 'forum_posts', type_='foreignkey')
    op.drop_constraint(None, 'forum_posts', type_='foreignkey')
    op.create_foreign_key('forum_posts_parent_id_fkey', 'forum_posts', 'forum_posts', ['parent_id'], ['id'])
    op.create_foreign_key('forum_posts_author_id_fkey', 'forum_posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key('forum_posts_thread_id_fkey', 'forum_posts', 'forum_threads', ['thread_id'], ['id'])
    op.drop_index('ix_forum_posts_user', table_name='forum_posts')
    op.drop_index('ix_forum_posts_thread_created', table_name='forum_posts')
    op.drop_index('ix_forum_posts_parent', table_name='forum_posts')
    op.create_index('ix_forum_posts_created_at', 'forum_posts', ['created_at'], unique=False)
    op.drop_column('forum_posts', 'edited_at')
    op.drop_column('forum_posts', 'user_id')
    op.drop_constraint(None, 'forum_likes', type_='foreignkey')
    op.drop_constraint(None, 'forum_likes', type_='foreignkey')
    op.create_foreign_key('forum_likes_post_id_fkey', 'forum_likes', 'forum_posts', ['post_id'], ['id'])
    op.create_foreign_key('forum_likes_user_id_fkey', 'forum_likes', 'users', ['user_id'], ['id'])
    op.drop_index('ix_forum_likes_user', table_name='forum_likes')
    op.drop_index('ix_forum_likes_post_user', table_name='forum_likes')
    op.add_column('forum_categories', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_forum_categories_slug', 'forum_categories', ['slug'], unique=True)
    op.alter_column('forum_categories', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###

