"""Add password reset fields to user

Revision ID: 15325a75a2d5
Revises: add_notification_settings
Create Date: 2025-11-17 22:30:13.579192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15325a75a2d5'
down_revision = 'add_notification_settings'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_settings_user_id_fkey', 'notification_settings', type_='foreignkey')
    op.create_foreign_key(None, 'notification_settings', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('reset_password_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_reset_password_code'), 'users', ['reset_password_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_password_code'), table_name='users')
    op.drop_column('users', 'reset_password_code_expires_at')
    op.drop_column('users', 'reset_password_code')
    op.drop_constraint(None, 'notification_settings', type_='foreignkey')
    op.create_foreign_key('notification_settings_user_id_fkey', 'notification_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

