"""add_seo_meta_fields_to_articles

Revision ID: e0771f4d9bb6
Revises: 4d32d5e75858
Create Date: 2025-12-07 15:57:07.585073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0771f4d9bb6'
down_revision = '4d32d5e75858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('meta_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'meta_description')
    op.drop_column('articles', 'meta_title')
    # ### end Alembic commands ###

