"""add_moderation_logs_table

Revision ID: cdea74cb1ca6
Revises: fa87c57590bf
Create Date: 2025-12-06 19:22:23.394672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdea74cb1ca6'
down_revision = 'fa87c57590bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('THREAD', 'POST', name='contenttype'), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='moderationdecision'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.JSON(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_created_at'), 'moderation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_logs_decision'), 'moderation_logs', ['decision'], unique=False)
    op.create_index(op.f('ix_moderation_logs_id'), 'moderation_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_logs_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_decision'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_created_at'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    # ### end Alembic commands ###

