"""Add users table with authentication fields

Revision ID: a2649ea01d0f
Revises: 1d9e8c88dd4d
Create Date: 2025-11-04 22:56:07.722319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2649ea01d0f'
down_revision = '1d9e8c88dd4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

